[package]
name = "common"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
prost = "0.13.3"
serde = { version = "1.0.210", features = ["derive"] }

[build-dependencies]
prost-build = "0.13.3"
